apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
        containers:
        - name: user-service
          image:  eu.gcr.io/hprofits/user-service:latest
          imagePullPolicy: Always
          command: [
            "./user-service",
            "--selector=static",
            "--registry=kubernetes",
            "--server_address=:8080"
          ]
          env:
          - name: COUCHBASE
            value: "couchbase://cb-example-srv"
          - name: COUCHBASE_BUCKET
            value: "test"
          - name: COUCHBASE_USER
            value: "Administrator"
          - name: COUCHBASE_PASSWORD
            value: "password"
          - name: MICRO_BROKER
            value: "nats"
          - name: MICRO_BROKER_ADDRESS
            value: "nats:4222"
          - name: NATS_STREAM
            value: "stan"
          - name: UPDATED_AT
            value: "Пт фев 15 16:55:04 MSK 2019"
          ports:
          - containerPort: 8080
            name: user-port