// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FirstName            string               `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string               `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	Type                 string               `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Service              string               `protobuf:"bytes,9,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d74fea83e22cc2cf, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *User) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type ID struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d74fea83e22cc2cf, []int{1}
}
func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (dst *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(dst, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListUsersRequest struct {
	Role                 uint32   `protobuf:"varint,1,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d74fea83e22cc2cf, []int{2}
}
func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (dst *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(dst, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

func (m *ListUsersRequest) GetRole() uint32 {
	if m != nil {
		return m.Role
	}
	return 0
}

type ListUsersByIDRequest struct {
	Ids                  []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersByIDRequest) Reset()         { *m = ListUsersByIDRequest{} }
func (m *ListUsersByIDRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersByIDRequest) ProtoMessage()    {}
func (*ListUsersByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d74fea83e22cc2cf, []int{3}
}
func (m *ListUsersByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersByIDRequest.Unmarshal(m, b)
}
func (m *ListUsersByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersByIDRequest.Marshal(b, m, deterministic)
}
func (dst *ListUsersByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersByIDRequest.Merge(dst, src)
}
func (m *ListUsersByIDRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersByIDRequest.Size(m)
}
func (m *ListUsersByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersByIDRequest proto.InternalMessageInfo

func (m *ListUsersByIDRequest) GetIds() []uint64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type ListUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d74fea83e22cc2cf, []int{4}
}
func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (dst *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(dst, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ListUsersResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type AuthUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthUserRequest) Reset()         { *m = AuthUserRequest{} }
func (m *AuthUserRequest) String() string { return proto.CompactTextString(m) }
func (*AuthUserRequest) ProtoMessage()    {}
func (*AuthUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d74fea83e22cc2cf, []int{5}
}
func (m *AuthUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthUserRequest.Unmarshal(m, b)
}
func (m *AuthUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthUserRequest.Marshal(b, m, deterministic)
}
func (dst *AuthUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthUserRequest.Merge(dst, src)
}
func (m *AuthUserRequest) XXX_Size() int {
	return xxx_messageInfo_AuthUserRequest.Size(m)
}
func (m *AuthUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthUserRequest proto.InternalMessageInfo

func (m *AuthUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthUserResponse struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthUserResponse) Reset()         { *m = AuthUserResponse{} }
func (m *AuthUserResponse) String() string { return proto.CompactTextString(m) }
func (*AuthUserResponse) ProtoMessage()    {}
func (*AuthUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d74fea83e22cc2cf, []int{6}
}
func (m *AuthUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthUserResponse.Unmarshal(m, b)
}
func (m *AuthUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthUserResponse.Marshal(b, m, deterministic)
}
func (dst *AuthUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthUserResponse.Merge(dst, src)
}
func (m *AuthUserResponse) XXX_Size() int {
	return xxx_messageInfo_AuthUserResponse.Size(m)
}
func (m *AuthUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthUserResponse proto.InternalMessageInfo

func (m *AuthUserResponse) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d74fea83e22cc2cf, []int{7}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*ID)(nil), "user.ID")
	proto.RegisterType((*ListUsersRequest)(nil), "user.ListUsersRequest")
	proto.RegisterType((*ListUsersByIDRequest)(nil), "user.ListUsersByIDRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "user.ListUsersResponse")
	proto.RegisterType((*AuthUserRequest)(nil), "user.AuthUserRequest")
	proto.RegisterType((*AuthUserResponse)(nil), "user.AuthUserResponse")
	proto.RegisterType((*Token)(nil), "user.Token")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserServiceClient interface {
	CreateUser(ctx context.Context, in *User, opts ...client.CallOption) (*User, error)
	GetUser(ctx context.Context, in *ID, opts ...client.CallOption) (*User, error)
	UpdateUser(ctx context.Context, in *User, opts ...client.CallOption) (*User, error)
	DeleteUser(ctx context.Context, in *ID, opts ...client.CallOption) (*ID, error)
	AuthUser(ctx context.Context, in *AuthUserRequest, opts ...client.CallOption) (*AuthUserResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...client.CallOption) (*ListUsersResponse, error)
	ListUsersByID(ctx context.Context, in *ListUsersByIDRequest, opts ...client.CallOption) (*ListUsersResponse, error)
	ValidateToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error)
}

type userServiceClient struct {
	c           client.Client
	serviceName string
}

func NewUserServiceClient(serviceName string, c client.Client) UserServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "user"
	}
	return &userServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *User, opts ...client.CallOption) (*User, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.CreateUser", in)
	out := new(User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *ID, opts ...client.CallOption) (*User, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.GetUser", in)
	out := new(User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *User, opts ...client.CallOption) (*User, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.UpdateUser", in)
	out := new(User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *ID, opts ...client.CallOption) (*ID, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.DeleteUser", in)
	out := new(ID)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AuthUser(ctx context.Context, in *AuthUserRequest, opts ...client.CallOption) (*AuthUserResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.AuthUser", in)
	out := new(AuthUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...client.CallOption) (*ListUsersResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.ListUsers", in)
	out := new(ListUsersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsersByID(ctx context.Context, in *ListUsersByIDRequest, opts ...client.CallOption) (*ListUsersResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.ListUsersByID", in)
	out := new(ListUsersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ValidateToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.ValidateToken", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	CreateUser(context.Context, *User, *User) error
	GetUser(context.Context, *ID, *User) error
	UpdateUser(context.Context, *User, *User) error
	DeleteUser(context.Context, *ID, *ID) error
	AuthUser(context.Context, *AuthUserRequest, *AuthUserResponse) error
	ListUsers(context.Context, *ListUsersRequest, *ListUsersResponse) error
	ListUsersByID(context.Context, *ListUsersByIDRequest, *ListUsersResponse) error
	ValidateToken(context.Context, *Token, *Token) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserService{hdlr}, opts...))
}

type UserService struct {
	UserServiceHandler
}

func (h *UserService) CreateUser(ctx context.Context, in *User, out *User) error {
	return h.UserServiceHandler.CreateUser(ctx, in, out)
}

func (h *UserService) GetUser(ctx context.Context, in *ID, out *User) error {
	return h.UserServiceHandler.GetUser(ctx, in, out)
}

func (h *UserService) UpdateUser(ctx context.Context, in *User, out *User) error {
	return h.UserServiceHandler.UpdateUser(ctx, in, out)
}

func (h *UserService) DeleteUser(ctx context.Context, in *ID, out *ID) error {
	return h.UserServiceHandler.DeleteUser(ctx, in, out)
}

func (h *UserService) AuthUser(ctx context.Context, in *AuthUserRequest, out *AuthUserResponse) error {
	return h.UserServiceHandler.AuthUser(ctx, in, out)
}

func (h *UserService) ListUsers(ctx context.Context, in *ListUsersRequest, out *ListUsersResponse) error {
	return h.UserServiceHandler.ListUsers(ctx, in, out)
}

func (h *UserService) ListUsersByID(ctx context.Context, in *ListUsersByIDRequest, out *ListUsersResponse) error {
	return h.UserServiceHandler.ListUsersByID(ctx, in, out)
}

func (h *UserService) ValidateToken(ctx context.Context, in *Token, out *Token) error {
	return h.UserServiceHandler.ValidateToken(ctx, in, out)
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_user_d74fea83e22cc2cf) }

var fileDescriptor_user_d74fea83e22cc2cf = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xd1, 0x6e, 0xd3, 0x40,
	0x10, 0x8c, 0x1d, 0xa7, 0xb1, 0x37, 0x0a, 0x84, 0x53, 0x0a, 0x96, 0x11, 0x22, 0x9c, 0x50, 0x14,
	0x09, 0x29, 0x91, 0xd2, 0x27, 0x84, 0x84, 0x14, 0x1a, 0x81, 0x22, 0x10, 0x0f, 0xa6, 0xe5, 0xb5,
	0xba, 0xc6, 0xdb, 0x62, 0x70, 0x62, 0xe3, 0x3b, 0xb7, 0xea, 0x8f, 0xf0, 0x0d, 0x7c, 0x26, 0xba,
	0x3d, 0x5f, 0x9a, 0x1a, 0x41, 0x5f, 0xaa, 0x9d, 0xd9, 0xd9, 0xb9, 0x7a, 0x76, 0x03, 0x87, 0x45,
	0x99, 0xab, 0x7c, 0x56, 0x49, 0x2c, 0xe9, 0xcf, 0x94, 0x30, 0xf3, 0x74, 0x1d, 0x3d, 0xbf, 0xcc,
	0xf3, 0xcb, 0x0c, 0x67, 0xc4, 0x9d, 0x57, 0x17, 0x33, 0x95, 0x6e, 0x50, 0x2a, 0xb1, 0x29, 0x8c,
	0x8c, 0xff, 0x76, 0xc1, 0x3b, 0x95, 0x58, 0xb2, 0x07, 0xe0, 0xa6, 0x49, 0xe8, 0x8c, 0x9c, 0x89,
	0x17, 0xbb, 0x69, 0xc2, 0x5e, 0x03, 0xac, 0x4b, 0x14, 0x0a, 0x93, 0x33, 0xa1, 0x42, 0x77, 0xe4,
	0x4c, 0x7a, 0xf3, 0x68, 0x6a, 0xec, 0xa6, 0xd6, 0x6e, 0x7a, 0x62, 0xed, 0xe2, 0xa0, 0x56, 0x2f,
	0x94, 0x1e, 0xad, 0x8a, 0xc4, 0x8e, 0xb6, 0xef, 0x1f, 0xad, 0xd5, 0x0b, 0xc5, 0x9e, 0x01, 0x5c,
	0xa4, 0xa5, 0x54, 0x67, 0x5b, 0xb1, 0xc1, 0xd0, 0x1b, 0x39, 0x93, 0x20, 0x0e, 0x88, 0xf9, 0x2c,
	0x36, 0xc8, 0x9e, 0x42, 0x90, 0x09, 0xdb, 0xed, 0x50, 0xd7, 0xd7, 0x04, 0x35, 0x87, 0xd0, 0xc1,
	0x8d, 0x48, 0xb3, 0xf0, 0x80, 0x1a, 0x06, 0xb0, 0x08, 0xfc, 0x42, 0x48, 0x79, 0x9d, 0x97, 0x49,
	0xd8, 0x35, 0x13, 0x16, 0x33, 0x06, 0x9e, 0xba, 0x29, 0x30, 0xf4, 0x89, 0xa7, 0x9a, 0x85, 0xd0,
	0x95, 0x58, 0x5e, 0xa5, 0x6b, 0x0c, 0x03, 0xa2, 0x2d, 0xe4, 0x43, 0x70, 0x57, 0xcb, 0x66, 0x4e,
	0x7c, 0x0c, 0x83, 0x4f, 0xa9, 0x54, 0x3a, 0x43, 0x19, 0xe3, 0xcf, 0x0a, 0xa5, 0xd2, 0xbe, 0x65,
	0x9e, 0x21, 0xa9, 0xfa, 0x31, 0xd5, 0x7c, 0x02, 0xc3, 0x9d, 0xee, 0xdd, 0xcd, 0x6a, 0x69, 0xb5,
	0x03, 0x68, 0xa7, 0x89, 0x0c, 0x9d, 0x51, 0x7b, 0xe2, 0xc5, 0xba, 0xe4, 0x1f, 0xe1, 0xd1, 0x9e,
	0xa3, 0x2c, 0xf2, 0xad, 0x44, 0x36, 0x82, 0x8e, 0x5e, 0xa8, 0x11, 0xf6, 0xe6, 0x30, 0xa5, 0x55,
	0x6b, 0x4d, 0x6c, 0x1a, 0xfa, 0xf3, 0xd7, 0x79, 0xb5, 0x35, 0xbb, 0xea, 0xc7, 0x06, 0xf0, 0x63,
	0x78, 0xb8, 0xa8, 0xd4, 0x37, 0x12, 0xd6, 0x2f, 0xee, 0x72, 0x72, 0xfe, 0x95, 0x93, 0x7b, 0x37,
	0x27, 0xfe, 0x12, 0x06, 0xb7, 0x26, 0xf5, 0x3f, 0x34, 0x80, 0xf6, 0xf7, 0x6b, 0x55, 0x7b, 0xe8,
	0x92, 0x1f, 0x41, 0xe7, 0x24, 0xff, 0x81, 0x5b, 0xfd, 0x80, 0xd2, 0x85, 0x7d, 0x40, 0x59, 0xf6,
	0x4a, 0x64, 0xa9, 0x71, 0xf7, 0x63, 0x03, 0xe6, 0xbf, 0xda, 0xd0, 0xd3, 0xbe, 0x5f, 0x4c, 0xc8,
	0x6c, 0x0c, 0x70, 0x4c, 0x87, 0x44, 0x47, 0xb9, 0xf7, 0x99, 0xd1, 0x5e, 0xcd, 0x5b, 0xec, 0x05,
	0x74, 0x3f, 0x20, 0x65, 0xc4, 0x7c, 0xd3, 0x58, 0x2d, 0x1b, 0x92, 0x31, 0xc0, 0x29, 0x1d, 0xd6,
	0x3d, 0x56, 0x1c, 0x60, 0x89, 0x19, 0xd6, 0xba, 0x5b, 0xb7, 0x5d, 0xc5, 0x5b, 0xec, 0x0d, 0xf8,
	0x36, 0x01, 0x76, 0x68, 0xf8, 0x46, 0xac, 0xd1, 0xe3, 0x26, 0x6d, 0x82, 0xe2, 0x2d, 0xf6, 0x16,
	0x82, 0xdd, 0x42, 0x59, 0x2d, 0x6b, 0xde, 0x4c, 0xf4, 0xe4, 0x2f, 0x7e, 0x37, 0xff, 0x1e, 0xfa,
	0x77, 0x4e, 0x87, 0x45, 0x0d, 0xed, 0xde, 0x3d, 0xfd, 0xcf, 0xe7, 0x15, 0xf4, 0xbf, 0xea, 0xd0,
	0x85, 0x42, 0xb3, 0xa8, 0x9e, 0xd1, 0x12, 0x88, 0xf6, 0x01, 0x6f, 0x9d, 0x1f, 0xd0, 0x0f, 0xf5,
	0xe8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x08, 0x70, 0xa1, 0x90, 0x5f, 0x04, 0x00, 0x00,
}
