// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FirstName            string               `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string               `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash         string               `protobuf:"bytes,7,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Type                 string               `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Service              string               `protobuf:"bytes,9,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_44df9c3e671c23ab, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *User) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *User) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_44df9c3e671c23ab, []int{1}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_44df9c3e671c23ab, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_44df9c3e671c23ab, []int{3}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_44df9c3e671c23ab, []int{4}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*Request)(nil), "user.Request")
	proto.RegisterType((*Response)(nil), "user.Response")
	proto.RegisterType((*Token)(nil), "user.Token")
	proto.RegisterType((*Error)(nil), "user.Error")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_user_44df9c3e671c23ab) }

var fileDescriptor_user_44df9c3e671c23ab = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x6d, 0x12, 0xdb, 0x89, 0xc7, 0xa4, 0x87, 0x11, 0x48, 0xab, 0x20, 0xc0, 0x38, 0x12, 0x2a,
	0x42, 0x72, 0xa4, 0x70, 0xe2, 0xc0, 0x21, 0x42, 0xa8, 0x9c, 0x38, 0x98, 0x82, 0xb8, 0x45, 0xdb,
	0x78, 0xda, 0x58, 0xd8, 0x59, 0x77, 0x77, 0x5d, 0xc4, 0x67, 0xf1, 0x31, 0xfc, 0x0f, 0xda, 0x59,
	0x5b, 0x0a, 0x15, 0x52, 0x7b, 0x49, 0x66, 0xde, 0x7b, 0xf3, 0xe4, 0x79, 0xb3, 0xf0, 0xa4, 0xd5,
	0xca, 0xaa, 0x55, 0x67, 0x48, 0xf3, 0x4f, 0xce, 0x3d, 0x06, 0xae, 0x5e, 0xbc, 0xb8, 0x56, 0xea,
	0xba, 0xa6, 0x15, 0x63, 0x97, 0xdd, 0xd5, 0xca, 0x56, 0x0d, 0x19, 0x2b, 0x9b, 0xd6, 0xcb, 0xb2,
	0xdf, 0x63, 0x08, 0xbe, 0x1a, 0xd2, 0x78, 0x0a, 0xe3, 0xaa, 0x14, 0xa3, 0x74, 0x74, 0x16, 0x17,
	0xe3, 0xaa, 0xc4, 0x77, 0x00, 0x3b, 0x4d, 0xd2, 0x52, 0xb9, 0x95, 0x56, 0x8c, 0xd3, 0xd1, 0x59,
	0xb2, 0x5e, 0xe4, 0xde, 0x2e, 0x1f, 0xec, 0xf2, 0x8b, 0xc1, 0xae, 0x88, 0x7b, 0xf5, 0xc6, 0xba,
	0xd1, 0xae, 0x2d, 0x87, 0xd1, 0xc9, 0xfd, 0xa3, 0xbd, 0x7a, 0x63, 0xf1, 0x19, 0xc0, 0x55, 0xa5,
	0x8d, 0xdd, 0x1e, 0x64, 0x43, 0x22, 0xe0, 0xaf, 0x89, 0x19, 0xf9, 0x2c, 0x1b, 0xc2, 0xa7, 0x10,
	0xd7, 0x72, 0x60, 0x43, 0x66, 0x67, 0x0e, 0x60, 0xf2, 0x31, 0x84, 0xd4, 0xc8, 0xaa, 0x16, 0x11,
	0x13, 0xbe, 0xc1, 0x25, 0xcc, 0x5b, 0x69, 0xcc, 0x4f, 0xa5, 0xcb, 0xed, 0x5e, 0x9a, 0xbd, 0x98,
	0x32, 0xfb, 0x68, 0x00, 0x3f, 0x49, 0xb3, 0x47, 0x84, 0xc0, 0xfe, 0x6a, 0x49, 0xcc, 0x98, 0xe3,
	0x1a, 0x05, 0x4c, 0x0d, 0xe9, 0xdb, 0x6a, 0x47, 0x22, 0x66, 0x78, 0x68, 0xb3, 0x18, 0xa6, 0x05,
	0xdd, 0x74, 0x64, 0x6c, 0x76, 0x03, 0xb3, 0x82, 0x4c, 0xab, 0x0e, 0x86, 0xf0, 0x39, 0x70, 0xe6,
	0x9c, 0x61, 0xb2, 0x86, 0x9c, 0x8f, 0xe1, 0xb2, 0x2d, 0x18, 0xc7, 0x14, 0x42, 0xf7, 0x6f, 0xc4,
	0x38, 0x9d, 0xdc, 0x11, 0x78, 0x02, 0x97, 0x10, 0x91, 0xd6, 0x4a, 0x1b, 0x31, 0x61, 0x49, 0xe2,
	0x25, 0x1f, 0x1d, 0x56, 0xf4, 0x54, 0xf6, 0x1d, 0xc2, 0x0b, 0xf5, 0x83, 0x0e, 0x6e, 0x5f, 0xeb,
	0x8a, 0xfe, 0x68, 0xbe, 0x71, 0xe8, 0xad, 0xac, 0xab, 0x92, 0x4f, 0x36, 0x2b, 0x7c, 0xf3, 0x30,
	0xe7, 0xf7, 0x10, 0x32, 0xe0, 0xe2, 0xd8, 0xa9, 0x92, 0xd8, 0x38, 0x2c, 0xb8, 0xc6, 0x14, 0x92,
	0x92, 0xcc, 0x4e, 0x57, 0xad, 0xad, 0xd4, 0x81, 0xdd, 0xe3, 0xe2, 0x18, 0x5a, 0xff, 0x19, 0x41,
	0xe2, 0xb6, 0xf9, 0xe2, 0x63, 0xc2, 0x57, 0x10, 0x7d, 0xe0, 0x37, 0x81, 0x47, 0xab, 0x2e, 0x4e,
	0x7d, 0x3d, 0xa4, 0x96, 0x9d, 0xe0, 0x12, 0x26, 0xe7, 0x64, 0xef, 0x11, 0xbd, 0x86, 0xe8, 0x9c,
	0xec, 0xa6, 0xae, 0x71, 0x3e, 0x70, 0x7c, 0x81, 0xff, 0x48, 0x5f, 0x42, 0xb0, 0xe9, 0xec, 0xfe,
	0x1f, 0xc3, 0x7e, 0x5f, 0x0e, 0x2e, 0x3b, 0xc1, 0x37, 0x30, 0xff, 0xe6, 0x72, 0x91, 0x96, 0x7c,
	0x96, 0xc7, 0xfc, 0x1d, 0xf1, 0x65, 0xc4, 0x4f, 0xf6, 0xed, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x93, 0xb8, 0x23, 0xe5, 0x69, 0x03, 0x00, 0x00,
}
